### ISSUE TITLE
如果能支持3.18.23就更好了！cmake报错

### ISSUE THREAD

**Issue by hzjnet** [syb999/openwrt-15.05#1]
如题，谢谢分享！

cmake错误如下：
/usr/bin/gmake -f CMakeFiles/cmTC_41956.dir/build.make CMakeFiles/cmTC_41956.dir/build
gmake[5]: Entering directory `/openwrt/openwrt-cc01-syb999-d191221-k109/build_dir/target-mips_34kc_uClibc-0.9.33.2/trojan-1.13.0/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_41956.dir/src.c.o
/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc   -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_41956.dir/src.c.o   -c /openwrt/openwrt-cc01-syb999-d191221-k109/build_dir/target-mips_34kc_uClibc-0.9.33.2/trojan-1.13.0/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_41956
/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/host/bin/cmake -E cmake_link_script CMakeFiles/cmTC_41956.dir/link.txt --verbose=1
/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-uclibc-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -DCMAKE_HAVE_LIBC_PTHREAD  -L/openwrt/openwrt-cc01-syb999-d191221-k109/build_dir/target-mips_34kc_uClibc-0.9.33.2/openssl1.1_staging_dir/usr/lib -L/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/lib -L/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/target-mips_34kc_uClibc-0.9.33.2/lib -L/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/lib -L/openwrt/openwrt-cc01-syb999-d191221-k109/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib -flto -Wl,--gc-sections  CMakeFiles/cmTC_41956.dir/src.c.o  -o cmTC_41956 
CMakeFiles/cmTC_41956.dir/src.c.o: In function `main':
src.c:(.text.startup+0x8): undefined reference to `pthread_create'
src.c:(.text.startup+0xe): undefined reference to `pthread_detach'
src.c:(.text.startup+0x16): undefined reference to `pthread_join'
src.c:(.text.startup+0x20): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
gmake[5]: *** [cmTC_41956] Error 1
gmake[5]: Leaving directory `/openwrt/openwrt-cc01-syb999-d191221-k109/build_dir/target-mips_34kc_uClibc-0.9.33.2/trojan-1.13.0/CMakeFiles/CMakeTmp'
gmake[4]: *** [cmTC_41956/fast] Error 2
gmake[4]: Leaving directory `/openwrt/openwrt-cc01-syb999-d191221-k109/build_dir/target-mips_34kc_uClibc-0.9.33.2/trojan-1.13.0/CMakeFiles/CMakeTmp'

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

**Comment by syb999** [comment]
Boost 1.66 relied on by Trojan,that required gcc 5 version. 
But chaos_calmer default use gcc 4.8.
I don't plan to upgrade GCC, which will cause the ipk to be incompatible with the official.

**Comment by syb999** [comment]
Fixed.  
git pull
make menuconfig & make V=99.
