### ISSUE TITLE
可以出一版如何把passwall或者ssr+移植到这个15.05版本上的教程吗？

### ISSUE THREAD

**Issue by BallM8964** [syb999/openwrt-15.05#17]
今天编译的时候出现了一个致命错误，tcpping.c:53:20: fatal error: libnet.h: No such file or directory
原来是要用libnet-1.2.x/lib -lnet -lpcap
一查这个是LEDE Release:LEDE-17.01.4以后的版本才有的。
诸如此类--

**Comment by syb999** [comment]
please use: git pull
now the libnet-1.2 dependency library has been added.
