### ISSUE TITLE
ssdk building error

### ISSUE THREAD

**Issue by hzjnet** [syb999/openwrt-15.05#2]
taging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo/fast-classifier.default.install
make[3]: Leaving directory `/openwrt/openwrt-cc01-syb999-d200110-k140/package/qca/fast-classifier'
make[3]: Entering directory `/openwrt/openwrt-cc01-syb999-d200110-k140/package/qca/qca-ssdk'
mkdir -p /openwrt/openwrt-cc01-syb999-d200110-k140/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/qca-ssdk-gdaf77c6; cp -fpR /openwrt/openwrt-cc01-syb999-d200110-k140/package/qca/qca-ssdk/src/* /openwrt/openwrt-cc01-syb999-d200110-k140/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/qca-ssdk-gdaf77c6/
cp: cannot stat '/openwrt/openwrt-cc01-syb999-d200110-k140/package/qca/qca-ssdk/src/*': No such file or directory

取消该选项能过；相反自己增加src下源码和qca-rfs也不行

**Comment by syb999** [comment]
Its closed-souce software.
