### ISSUE TITLE
iptables-1.6.2编译不过,手动下载后仍然报错

### ISSUE THREAD

**Issue by liugengrong** [syb999/openwrt-15.05#21]
make[3]: Leaving directory `/home/liugengrong/openwrt-15.05/package/libs/uclient'
make[3]: Entering directory `/home/liugengrong/openwrt-15.05/package/network/utils/iptables'
. /home/liugengrong/openwrt-15.05/include/shell.sh; xzcat /home/liugengrong/openwrt-15.05/dl/iptables-1.6.2.tar.xz | tar -C /home/liugengrong/openwrt-15.05/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.6.2/.. -xf - 

Applying ./patches/020-iptables-disable-modprobe.patch using plaintext: 
patching file libxtables/xtables.c
Hunk #1 succeeded at 420 (offset 65 lines).
Hunk #2 succeeded at 455 (offset 59 lines).

Applying ./patches/030-extensions-libxt_bpf-Fix-build-with-old-kernel-versi.patch using plaintext: 
patching file extensions/libxt_bpf.c
Hunk #1 FAILED at 22.
Hunk #2 FAILED at 62.
2 out of 2 hunks FAILED -- saving rejects to file extensions/libxt_bpf.c.rej
Patch failed!  Please fix ./patches/030-extensions-libxt_bpf-Fix-build-with-old-kernel-versi.patch!
make[3]: *** [/home/liugengrong/openwrt-15.05/build_dir/target-mips_34kc_uClibc-0.9.33.2/linux-ar71xx_generic/iptables-1.6.2/.prepared_8fcd71e2405bc2b62ef794e46c6945c2] Error 1
make[3]: Leaving directory `/home/liugengrong/openwrt-15.05/package/network/utils/iptables'
make[2]: *** [package/network/utils/iptables/compile] Error 2
make[2]: Leaving directory `/home/liugengrong/openwrt-15.05'
make[1]: *** [/home/liugengrong/openwrt-15.05/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/liugengrong/openwrt-15.05'

一直报错,手动下载iptables-1.6.2还是不行,之间报错git clone https iptables-1.6.2无法下载

**Comment by syb999** [comment]
报错日志：030-extensions-libxt_bpf-Fix-build-with-old-kernel-versi.patch补丁偏移不对，导致补丁打不上。
请确认是否给iptables添加了额外补丁，如果有。自己diff修改补丁。
或者重新下载源码。

**Comment by liugengrong** [comment]
Checking out files from the git repository...
Cloning into 'iptables-1.6.2'...
error: Unknown SSL protocol error in connection to git.netfilter.org:443  (curl_result = 35, http_code = 0, sha1 = 1b7400050c0ed1653ef9305259924525f14c28af)
error: Unable to find 1b7400050c0ed1653ef9305259924525f14c28af under https://git.netfilter.org/iptables
Fetching objects: 7386, done.
Cannot obtain needed blob 1b7400050c0ed1653ef9305259924525f14c28af
while processing commit b3ac87038f4e45141831d9ab485a2f627daba3f1.
error: fetch failed.
make[3]: *** [/home/liugengrong/openwrt-15.05/dl/iptables-1.6.2.tar.xz] Error 128
make[3]: Leaving directory `/home/liugengrong/openwrt-15.05/package/network/utils/iptables'
make[2]: *** [package/network/utils/iptables/compile] Error 2
make[2]: Leaving directory `/home/liugengrong/openwrt-15.05'
make[1]: *** [/home/liugengrong/openwrt-15.05/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/liugengrong/openwrt-15.05'
make: *** [world] Error 2

删除后,重新git clone源码,什么都没做,执行以下命令后报错如上
./scripts/feeds update -a
./scripts/feeds install -a
make V=99

**Comment by syb999** [comment]
报错日志:error: Unknown SSL protocol error in connection to git.netfilter.org:443

这是你网络的问题，导致无法下载.

**Comment by liugengrong** [comment]
> 报错日志:error: Unknown SSL protocol error in connection to git.netfilter.org:443
> 
> 这是你网络的问题，导致无法下载.

Thanks for you reply.

我手动是的可以下载下来的,一直卡在这边手动下载后报错如1楼的log,昨天试着把这个路径下openwrt-15.05/package/network/utils/所有的文件换成官方15.05的iptables-1.4.21的文件编译通过.貌似后面又报错了,test log如下,帮忙看下又是哪里出问题了呢? 尝试make clean并无效果,同样报错

make[3]: Leaving directory `/home/liugengrong/openwrt-15.05/package/utils/busybox'
make[2]: Leaving directory `/home/liugengrong/openwrt-15.05'
make[2]: Entering directory `/home/liugengrong/openwrt-15.05'
find /home/liugengrong/openwrt-15.05/staging_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx -type d | xargs -r chmod 0755
rm -rf /home/liugengrong/openwrt-15.05/build_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx
[ -d /home/liugengrong/openwrt-15.05/build_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx/tmp ] || mkdir -p /home/liugengrong/openwrt-15.05/build_dir/target-mips_34kc_uClibc-0.9.33.2/root-ar71xx/tmp
Collected errors:
 * pkg_init_from_file: Malformed package file /home/liugengrong/openwrt-15.05/bin/ar71xx/packages/base/base-files_157.3-unknown_ar71xx.ipk.
xargs: /home/liugengrong/openwrt-15.05/staging_dir/host/bin/opkg: exited with status 255; aborting
make[2]: *** [package/install] Error 124
make[2]: Leaving directory `/home/liugengrong/openwrt-15.05'
make[1]: *** [/home/liugengrong/openwrt-15.05/staging_dir/target-mips_34kc_uClibc-0.9.33.2/stamp/.package_install] Error 2
make[1]: Leaving directory `/home/liugengrong/openwrt-15.05'
make: *** [world] Error 2

**Comment by syb999** [comment]
make dirclean后重新编译

**Comment by liugengrong** [comment]
> make dirclean后重新编译

感谢答复,以执行,仍然报错,建议大佬实际自己编译下,放弃了.

**Comment by syb999** [comment]
一直在更新，一直在编译固件，编译很正常。
