### ISSUE TITLE
最新编译错误请教

### ISSUE THREAD

**Issue by hzjnet** [syb999/openwrt-15.05#23]
环境：
lsb_release -ra
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

 gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

1 选中luci-app-npc luci-app-nps出现以下错误：
make[3]: Entering directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/feeds/packages/net/npc'
mkdir -p /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/bin/ar71xx/packages /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/npc/ipkg-ar71xx/npc/CONTROL /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/staging_dir/target-mips_34kc_uClibc-0.9.33.2/pkginfo
install -d -m0755 /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/npc/ipkg-ar71xx/npc/usr/bin
install -m0755 /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/npc/nps/npc /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/npc/ipkg-ar71xx/npc/usr/bin/
install: cannot stat '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/npc/nps/npc': No such file or directory
make[3]: *** [/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/bin/ar71xx/packages/packages/npc_0.23.2-1_ar71xx.ipk] Error 1
Makefile:71: recipe for target '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/bin/ar71xx/packages/packages/npc_0.23.2-1_ar71xx.ipk' failed
make[3]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/feeds/packages/net/npc'
make[2]: *** [package/feeds/packages/npc/compile] Error 2
package/Makefile:191: recipe for target 'package/feeds/packages/npc/compile' failed

2选中luci-app-ushare出现以下错误：
image_jpeg.c: In function 'probe_jpeg':
image_jpeg.c:95:31: error: 'CODEC_ID_MJPEG' undeclared (first use in this function)
   if (codecs->vc->codec_id != CODEC_ID_MJPEG &&
                               ^
image_jpeg.c:95:31: note: each undeclared identifier is reported only once for each function it appears in
image_jpeg.c:96:31: error: 'CODEC_ID_MJPEGB' undeclared (first use in this function)
       codecs->vc->codec_id != CODEC_ID_MJPEGB &&
                               ^
image_jpeg.c:97:31: error: 'CODEC_ID_LJPEG' undeclared (first use in this function)
       codecs->vc->codec_id != CODEC_ID_LJPEG &&
                               ^
image_jpeg.c:98:31: error: 'CODEC_ID_JPEGLS' undeclared (first use in this function)
       codecs->vc->codec_id != CODEC_ID_JPEGLS)
                               ^
make[5]: *** [image_jpeg.o] Error 1
Makefile:66: recipe for target 'image_jpeg.o' failed
make[5]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/libdlna-0.2.4/src'
Makefile:31: recipe for target 'lib' failed
make[4]: *** [lib] Error 2
make[4]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/libdlna-0.2.4'
make[3]: *** [/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/libdlna-0.2.4/.built] Error 2
make[2]: *** [package/libs/libdlna/compile] Error 2
Makefile:81: recipe for target '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/build_dir/target-mips_34kc_uClibc-0.9.33.2/libdlna-0.2.4/.built' failed
make[3]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16-d211220-ar71xx-2-gcc7/package/libs/libdlna'
package/Makefile:191: recipe for target 'package/libs/libdlna/compile' failed

请教如何处理才能正常编译，谢谢

**Comment by syb999** [comment]
1. npc未发现问题。 请自行检查你的npc的Makefile里是否有下面这行命令：
    UNPACK_CMD=tar -zxvf "$(DL_DIR)/$(PKG_SOURCE)" -C $(PKG_BUILD_DIR)

2. libdlna 已添加兼容ffmpeg高版本的补丁。
    git pull 更新代码即可解结果。

**Comment by hzjnet** [comment]
> 1. npc未发现问题。 请自行检查你的npc的Makefile里是否有下面这行命令：
>    UNPACK_CMD=tar -zxvf "$(DL_DIR)/$(PKG_SOURCE)" -C $(PKG_BUILD_DIR)
> 2. libdlna 已添加兼容ffmpeg高版本的补丁。
>    git pull 更新代码即可解结果。

收到，谢谢回复

1 确认有该行
2 源码更新后ushare编译还是有问题，log如下

/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/build_dir/target-mips_34kc_uClibc-0.9.33.2/ushare-1.1a$ cat config.log
Checking for libthreadutil ...
check_lib upnp/ThreadPool.h ThreadPoolAdd -lthreadutil -lpthread
check_header upnp/ThreadPool.h
check_cpp
BEGIN /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/tmp/ushare--16804-.c
     1  #include <upnp/ThreadPool.h>
     2  int x;
END /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/tmp/ushare--16804-.c
mips-openwrt-linux-uclibc-gcc -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -I.. -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -DHAVE_LOCALE_H -DHAVE_SETLOCALE -DHAVE_IFADDRS_H -DHAVE_LANGINFO_H -DHAVE_LANGINFO_CODESET -E -o /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/tmp/ushare--16804-.o /openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/tmp/ushare--16804-.c
/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220104-ar71xx-2/tmp/ushare--16804-.c:1:29: fatal error: upnp/ThreadPool.h: No such file or directory

**Comment by syb999** [comment]
git pull先升级ushare至2.1版本。
由于ushare-2.1依赖libupnp 1.14.x版本.故需要更新feeds
./scripts/feeds update packages
./scripts/feeds install -a -p packages
然后编译即可。 测试ar71xx顺利通过编译。
