### ISSUE TITLE
最新ushare-2.1编译问题

### ISSUE THREAD

**Issue by hzjnet** [syb999/openwrt-15.05#24]
环境：
lsb_release -ra
LSB Version: core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description: Ubuntu 16.04.7 LTS
Release: 16.04
Codename: xenial

gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

具体log如下：
mips-openwrt-linux-uclibc-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include  -Os -pipe -mno-branch-likely -mips32r2 -mtune=74kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/target-mips_34kc_uClibc-0.9.33.2/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/include -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -DHAVE_LOCALE_H -DHAVE_SETLOCALE -DHAVE_IFADDRS_H -DHAVE_LANGINFO_H -DHAVE_LANGINFO_CODESET -pthread -I/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/staging_dir/target-mips_34kc_uClibc-0.9.33.2/usr/include/upnp -DHAVE_DLNA -o mime.o mime.c
cc1: note: someone does not honour COPTS correctly, passed 2 times
mime.c: In function 'mime_get_protocol':
mime.c:148:3: error: format not a string literal and no format arguments [-Werror=format-security]
   sprintf (protocol, mime->mime_protocol);
   ^
mime.c:148:3: error: format not a string literal and no format arguments [-Werror=format-security]
cc1: some warnings being treated as errors
make[5]: *** [mime.o] Error 1
Makefile:56: recipe for target 'mime.o' failed
make[5]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/build_dir/target-mips_34kc_uClibc-0.9.33.2/ushare-2.1/src'
make[4]: *** [all] Error 2
Makefile:22: recipe for target 'all' failed
make[4]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/build_dir/target-mips_34kc_uClibc-0.9.33.2/ushare-2.1'
make[3]: *** [/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/build_dir/target-mips_34kc_uClibc-0.9.33.2/ushare-2.1/.built] Error 2
Makefile:82: recipe for target '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/build_dir/target-mips_34kc_uClibc-0.9.33.2/ushare-2.1/.built' failed
make[3]: Leaving directory '/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1/package/multimedia/ushare'
make[2]: *** [package/multimedia/ushare/compile] Error 2
package/Makefile:191: recipe for target 'package/multimedia/ushare/compile' failed

请教如何处理，谢谢

**Comment by syb999** [comment]
ushare-2.1依赖libupnp 1.14.x版本.请先更新feeds
./scripts/feeds update packages
./scripts/feeds install -a -p packages
然后编译即可。 测试ar71xx顺利通过编译。

**Comment by hzjnet** [comment]
> libupnp

那就奇怪了，我选用941v7,是最新源码啊：
/openwrt/openwrt-1505/openwrt-syb999-15.05-M-ub16osgcc7-d220107-ar71xx-1$ cat feeds/packages/libs/libupnp/Makefile
include $(TOPDIR)/rules.mk                        
PKG_NAME:=libupnp
PKG_VERSION:=1.14.5
PKG_RELEASE:=1
用你上面2行还是一样问题提示，再看看

**Comment by syb999** [comment]
删了build_dir和staging_dir目录，重新编译即可。
