### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by Heporis** [syb999/openwrt-15.05#25]
想编译mdk4到固件里，用官方最新固件加mdk4的makefile会报错，然后直接clone这个15.05的固件来编译也会报错。
官方固件源码用这个[软件源](https://github.com/adde88/openwrt-useful-tools-src)编译也报错。要怎么修改makefile啊？

**Comment by Heporis** [comment]
15.05报错：
make[7]: Entering directory '/home/gesla/openwrt-15.05/build_dir/host/m4-1.4.17/lib'
depbase=`echo gl_avltree_oset.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc  -I.   -I/home/gesla/openwrt-15.05/staging_dir/host/include   -O2 -I/home/gesla/openwrt-15.05/staging_dir/host/include  -MT gl_avltree_oset.o -MD -MP -MF $depbase.Tpo -c -o gl_avltree_oset.o gl_avltree_oset.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo binary-io.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc  -I.   -I/home/gesla/openwrt-15.05/staging_dir/host/include   -O2 -I/home/gesla/openwrt-15.05/staging_dir/host/include  -MT binary-io.o -MD -MP -MF $depbase.Tpo -c -o binary-io.o binary-io.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo c-stack.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc  -I.   -I/home/gesla/openwrt-15.05/staging_dir/host/include   -O2 -I/home/gesla/openwrt-15.05/staging_dir/host/include  -MT c-stack.o -MD -MP -MF $depbase.Tpo -c -o c-stack.o c-stack.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
make[7]: *** [Makefile:1837: c-stack.o] Error 1
make[7]: Leaving directory '/home/gesla/openwrt-15.05/build_dir/host/m4-1.4.17/lib'
make[6]: *** [Makefile:1602: all] Error 2
make[6]: Leaving directory '/home/gesla/openwrt-15.05/build_dir/host/m4-1.4.17/lib'
make[5]: *** [Makefile:1506: all-recursive] Error 1
make[5]: Leaving directory '/home/gesla/openwrt-15.05/build_dir/host/m4-1.4.17'
make[4]: *** [Makefile:1461: all] Error 2
make[4]: Leaving directory '/home/gesla/openwrt-15.05/build_dir/host/m4-1.4.17'
make[3]: *** [Makefile:29: /home/gesla/openwrt-15.05/build_dir/host/m4-1.4.17/.built] Error 2
make[3]: Leaving directory '/home/gesla/openwrt-15.05/tools/m4'
make[2]: *** [tools/Makefile:129: tools/m4/compile] Error 2
make[2]: Leaving directory '/home/gesla/openwrt-15.05'
make[1]: *** [tools/Makefile:127: /home/gesla/openwrt-15.05/staging_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/stamp/.tools_install_yyynyynyyynyyyyyyyyyyynyyyyyyyyyyyyyyyyynnyyynnyyynynyy] Error 2
make[1]: Leaving directory '/home/gesla/openwrt-15.05'
make: *** [/home/gesla/openwrt-15.05/include/toplevel.mk:183: world] Error 2

**Comment by syb999** [comment]
第一个问题，那个Makefile不是给本地编译用的。使用了github的软链接。要修改。
第二个问题，你上面的报错日志是编译工具链m4包的报错问题。请确保编译环境。
推荐使用Ubuntu或者deepin来编译。根据README.MD要求，正确安装依赖包。确保你的bashrcsh环境没有添加额外的path。

**Comment by syb999** [comment]
> 想编译mdk4到固件里，用官方最新固件加mdk4的makefile会报错，然后直接clone这个15.05的固件来编译也会报错。 官方固件源码用这个[软件源](https://github.com/adde88/openwrt-useful-tools-src)编译也报错。要怎么修改makefile啊？

这是上面源使用的mdk4.1版本的推送。支持使用openwr官方稳定版本21.02、22.03分支的mdk4的package。我已同时修复了其Makefile与编译报错问题：
https://github.com/syb999/openwrt-22.03.5/commit/2328bb4de0771f51115c4f5780937d280e6fde84

**Comment by Heporis** [comment]
编译成功了，谢谢！

**Comment by Heporis** [comment]
In file included from /usr/include/signal.h:328,
from ./signal.h:52,
from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
| ^~~~~~~~
make[7]: *** [Makefile:1837: c-stack.o] Error 1

原因：m4版本过低 / Ubuntu版本过高

cd tools/m4/patches
wget https://raw.githubusercontent.com/keyfour/openwrt/2722d51c5cf6a296b8ecf7ae09e46690403a6c3d/tools/m4/patches/011-fix-sigstksz.patch

elf.hpp:52:56: error: ISO C++17 does not allow dynamic exception specifications

https://git.freifunk-franken.de/mirror/openwrt/commit/a1ee0ebbd8e9927a65c5d1e0db497dd118d559a6
![image](https://github.com/syb999/openwrt-15.05/assets/51895154/2a21b026-5c56-4f14-886d-c607a816ae12)

**Comment by syb999** [comment]
> In file included from /usr/include/signal.h:328, from ./signal.h:52, from c-stack.c:49: c-stack.c:55:26: error: missing binary operator before token "(" 55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384 | ^~~~~~~~ make[7]: *** [Makefile:1837: c-stack.o] Error 1
> 
> 原因：m4版本过低 / Ubuntu版本过高
> 
> cd tools/m4/patches wget https://raw.githubusercontent.com/keyfour/openwrt/2722d51c5cf6a296b8ecf7ae09e46690403a6c3d/tools/m4/patches/011-fix-sigstksz.patch
> 
> elf.hpp:52:56: error: ISO C++17 does not allow dynamic exception specifications
> 
> https://git.freifunk-franken.de/mirror/openwrt/commit/a1ee0ebbd8e9927a65c5d1e0db497dd118d559a6 ![image](https://user-images.githubusercontent.com/51895154/269976254-2a21b026-5c56-4f14-886d-c607a816ae12.png)

thx,merged.
