### ISSUE TITLE
能不能搞一个品胜路由器可以内置声卡芯片的3.18.20或者3.18.23。

### ISSUE THREAD

**Issue by openwrt-1983** [syb999/openwrt-15.05#26]
主要是因为可以用官方image直接编译固件，这样的话就不会提示komd内核不符的问题了  快速编译固件可以直接用官方库

**Comment by openwrt-1983** [comment]
我搞了好几天。修改了好多次补丁。有的可以成功，但是不能启动，有的就是各种错误。  🤣个人能力太差了。

**Comment by syb999** [comment]
品胜的内置声卡芯片驱动早已支持。
https://github.com/syb999/openwrt-15.05/commit/d62e982b2626e4bdd8180e893f5379942f578763
可以参考自己添加。

**Comment by openwrt-1983** [comment]
> 品胜的内置声卡芯片驱动早已支持。
> https://github.com/syb999/openwrt-15.05/commit/d62e982b2626e4bdd8180e893f5379942f578763
> 可以参考自己添加。

好的谢谢 我修改试试

**Comment by openwrt-1983** [comment]
> 品胜的内置声卡芯片驱动早已支持。
> https://github.com/syb999/openwrt-15.05/commit/d62e982b2626e4bdd8180e893f5379942f578763
> 可以参考自己添加。


我直接替换的你的 ar71xx文件夹 修改补丁文件  🤣 可能是哪里修改的不对 编译成功 breed刷进去不能启动

算了 我还是用你的140源码 把Kernel modules
里面所有的 kmod-xxx 全部选择<M>编译出来带上SDK和image 以后编译需要

**Comment by syb999** [comment]
不能启动可能和breed型号有关。换[breed-ar9331.bin/breed-ar9341.bin/breed-ar9344.bin刷机试一试。不同的breed读取的firmware位置不同,会导致无法启动。

**Comment by openwrt-1983** [comment]
> 不能启动可能和breed型号有关。换[breed-ar9331.bin/breed-ar9341.bin/breed-ar9344.bin刷机试一试。不同的breed读取的firmware位置不同,会导致无法启动。

还有这个问题 ?  真的不知道呢  我测试一下  但是用你的140源码编译的就可以成功启动
