### ISSUE TITLE
building openssl error

### ISSUE THREAD

**Issue by hzjnet** [syb999/openwrt-15.05#3]
bufferevent_openssl.c:235:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:236:2: warning: excess elements in struct initializer [enabled by default]
  bio_bufferevent_free,
  ^
bufferevent_openssl.c:236:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c:237:2: warning: excess elements in struct initializer [enabled by default]
  NULL /* callback_ctrl */,
  ^
bufferevent_openssl.c:237:2: warning: (near initialization for 'methods_bufferevent') [enabled by default]
bufferevent_openssl.c: In function 'BIO_new_bufferevent':
bufferevent_openssl.c:257:8: error: dereferencing pointer to incomplete type
  result->init = 1;
        ^
bufferevent_openssl.c:258:8: error: dereferencing pointer to incomplete type
  result->ptr = bufferevent;
        ^
bufferevent_openssl.c:259:8: error: dereferencing pointer to incomplete type
  result->shutdown = close_flag ? 1 : 0;
        ^
make[6]: *** [bufferevent_openssl.lo] Error 1

听说d版问题多建议不升级改版，回滚老版本正常

**Comment by syb999** [comment]
libevent2 need Update for support openssl1.1.1.
Now Fixed! 
git pull
