### ISSUE TITLE
npc nps transmission编译错误

### ISSUE THREAD

**Issue by hzjnet** [syb999/openwrt-15.05#4]
1 npc,具体错误如下：
install: cannot stat '/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/npc/nps/npc': No such file or directory
make[3]: *** [/xxxx/bin/ar71xx/packages/packages/npc_0.23.2-1_ar71xx.ipk] Error 1
make[3]: Leaving directory `/xxxx/feeds/packages/net/npc'
make[2]: *** [package/feeds/packages/npc/compile] Error 2
修改源码feeds/packages/net/npc/Makefile如下解决：
diff Makefile Makefile.sou
68c68
<       $(INSTALL_BIN) $(PKG_BUILD_DIR)/nps/npc $(1)/usr/bin/
>       $(INSTALL_BIN) $(PKG_BUILD_DIR)/npc $(1)/usr/bin/

2 nps,具体错误如下：
make[3]: Entering directory `/xxxx/feeds/packages/net/nps'
. /xxxx/include/shell.sh; gzip -dc /xxxx/dl/linux_mipsle_server.tar.gz | tar -C /xxxx/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/nps/.. -xf - 
touch /xxxx/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/nps/.prepared_9d6c58ade91d17b2f12cad9237cee942
touch: cannot touch '/xxxx/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/nps/.prepared_9d6c58ade91d17b2f12cad9237cee942': Not a directory
make[3]: *** [/xxxx/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/nps/.prepared_9d6c58ade91d17b2f12cad9237cee942] Error 1
make[3]: Leaving directory `/xxxx/feeds/packages/net/nps'
知道问题是build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/nps/ 目录不存在，但是不知道如何解决
3transmission错误：
make[6]: Entering directory `/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/transmission-2.84/third-party/libutp'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/transmission-2.84/third-party/libutp'
make[6]: Entering directory `/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/transmission-2.84/third-party'
make[6]: Nothing to be done for `all-am'.
make[6]: Leaving directory `/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/transmission-2.84/third-party'
make[5]: Leaving directory `/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/transmission-2.84/third-party'
Making all in libtransmission
make[5]: Entering directory `/xxxx/build_dir/target-mips_34kc_uClibc-0.9.33.2/transmission-2.84/libtransmission'
  CC       crypto.o
crypto.c: In function 'ensureKeyExists':
crypto.c:98:9: error: dereferencing pointer to incomplete type
       dh->p = BN_bin2bn (dh_P, sizeof (dh_P), NULL);
         ^
crypto.c:99:13: error: dereferencing pointer to incomplete type

谢谢！

**Comment by syb999** [comment]
1.about npc/nps: I didn't find the problem that you described.
2.transmission fixed:
./scripts/feeds update -a
./scripts/feeds install -a
